lib: [
  "_build/install/default/lib/ppx_dryunit/META" {"META"}
  "_build/install/default/lib/ppx_dryunit/opam" {"opam"}
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.cmi"
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.cmx"
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.cmt"
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.cmti"
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.mli"
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.cma"
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.cmxa"
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.a"
  "_build/install/default/lib/ppx_dryunit/ppx_dryunit.cmxs"
]
libexec: [
  "_build/install/default/lib/ppx_dryunit/ppx.exe"
]
doc: [
  "_build/install/default/doc/ppx_dryunit/README.md"
]
